name: Issue Creator
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Add commit comment
        run: |
        curl -X POST -u pawarashish564:token ${{ secrets.GITHUB_TOKEN }} -d "{"title":"Issue","body": "issues","labels": ["enhancement"]}" https://api.github.com/repos/pawarashish564/$GITHUB_REPOSITORY/issues
          # jq -nc '{"title": "Issue Title","body": "Issue description"}' | \
          # curl -sL  -X POST -d @- -u <UserName>:<Generated-Token> \
          #   -H "Content-Type: application/json" \
          #   -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          #   "https://api.github.com/repos/pawarashish564/$GITHUB_REPOSITORY/issues"
