name: Issue Creator
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Add commit comment
        run: |
          curl -X POST -i -d '{"title":"my-new-repo-issue","body":"my new issue description"}' https://api.github.com/repos/pawarashish564/Github-actions-bot-tutorial/issues
          
