
name: PR Creator
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Create A PR
        uses: technote-space/create-pr-action@v2
        with:
          EXECUTE_COMMANDS: |
            export num=$(od -An -N2 -i /dev/random) 
            echo "Hello code $num" >> fileData.txt    
            COMMIT_MESSAGE: 'Added data'
            COMMIT_NAME: 'GitHub Actions'
            COMMIT_EMAIL: 'example@example.com'
            PR_BRANCH_NAME: 'data-update-${PR_ID}'
            PR_TITLE: 'PR From the Bot'