name: commit comment
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Add commit comment
        run: |
          # git clone https://github.com/pawarashish564/Infinite-Series-Calculator.git
          # cd Infinite-Series-Calculator
          # export ver="hello world from the GITHUB BOT"
          uname -a >> demo
          export ver=$(cat demo)
          jq -nc '{"body":env.ver}' | \
          curl -sL  -X POST -d @- \
            -H "Content-Type: application/json" \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/$GITHUB_REPOSITORY/commits/$GITHUB_SHA/comments"
  
